name: Build
run-name: ${{ github.actor }} is building new tailscale packages
on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/tailscale/tailscale
  REPO_TAG: v1.40.1
  REPO_DEPTH: 1

permissions:
  contents: write

jobs:
  build-mips-le:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Initialization environment
      #   run: |
      #     sudo mkdir -p /workdir
      #     sudo chown $USER:$GROUPS /workdir
      - name: Clone tailscale repo
        # working-directory: /workdir
        run: |
          echo $REPO_URL
          echo $REPO_TAG
          git clone --depth $REPO_DEPTH --branch $REPO_TAG $REPO_URL
        #  ln -sf /workdir/tailscale $GITHUB_WORKSPACE/tailscale
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y binutils-mipsel-linux-gnu
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Build tailscale
        env:
          OS: linux
          ARCH: mipsle
          MIPS: softfloat
        run: |
          pwd
          ls -la
          pushd tailscale
          GOOS=$OS GOARCH=$ARCH GOMIPS=$MIPS go build -o tailscale.combined -tags ts_include_cli -trimpath -ldflags="-s -w" ./cmd/tailscaled
          mv tailscale.combined ../tailscale_mipsle.combined
          popd
          ls -lah
      - name: Compression tailscale
        uses: crazy-max/ghaction-upx@v2
        with:
          version: latest
          args: --lzma --best
          files: |
            ./tailscale_mipsle.combined
      - run: ls -lah
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: MIPS LE
          tag_name: ${{ env.REPO_TAG }}
          files: ./tailscale_mipsle.combined
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Create a Release
      #   uses: elgohr/Github-Release-Action@v4
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      #   with:
      #     title: MyReleaseMessage
